# Generated by Django 5.0.7 on 2024-07-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('contact', models.IntegerField(max_length=25, null=True)),
                ('email', models.EmailField(max_length=25, null=True)),
                ('id_proof', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='International_students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, null=True)),
                ('nation', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('university', models.CharField(max_length=100, null=True)),
                ('contact', models.IntegerField(max_length=25, null=True)),
                ('email', models.EmailField(max_length=25, null=True)),
                ('id_proof', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
