# Generated by Django 5.0.7 on 2024-07-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_home_students_international_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_students',
            name='qualification',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='international_students',
            name='address',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='international_students',
            name='course',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='home_students',
            name='address',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='home_students',
            name='contact',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='home_students',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='international_students',
            name='contact',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='international_students',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
