# Generated by Django 5.0.7 on 2024-07-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_home_students_qualification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_students',
            name='approvel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='international_students',
            name='approvel',
            field=models.BooleanField(default=False),
        ),
    ]
