# Generated by Django 5.0.7 on 2024-07-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_home_students_login_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_universites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('location', models.CharField(max_length=250, null=True)),
                ('link', models.CharField(max_length=250, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
