# Generated by Django 5.0.7 on 2024-07-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_add_universites'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_universites',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
