# Generated by Django 5.0.7 on 2024-07-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_add_universites_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_universites',
            name='requirment',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
