# Generated by Django 5.0.7 on 2024-07-19 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_add_universites_requirment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_universites',
            old_name='requirment',
            new_name='requirements',
        ),
    ]
