# Generated by Django 5.0.7 on 2024-07-19 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_requirment_add_universites_requirements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=50, null=True)),
                ('details', models.CharField(max_length=150, null=True)),
                ('requirements', models.CharField(max_length=500, null=True)),
                ('uni_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.add_universites')),
            ],
        ),
    ]
