# Generated by Django 5.0.7 on 2024-07-20 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_add_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_course',
            name='level',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
