# Generated by Django 5.0.7 on 2024-07-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_add_course_c_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('contact', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
