# Generated by Django 5.0.7 on 2024-07-23 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_add_agency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_agency',
            old_name='name',
            new_name='agency',
        ),
    ]
