# Generated by Django 5.0.7 on 2024-07-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_rename_name_add_agency_agency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_universites',
            old_name='image',
            new_name='image_main',
        ),
        migrations.AddField(
            model_name='add_universites',
            name='image_sub',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
