# Generated by Django 5.0.7 on 2024-07-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_add_course_application_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_agency',
            name='location',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
