# Generated by Django 5.0.7 on 2024-07-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_add_agency_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_agency',
            name='link',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
