# Generated by Django 5.0.7 on 2024-07-25 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_add_agency_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('posted_date', models.DateField(null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('i_student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.international_students')),
            ],
        ),
    ]
