# Generated by Django 5.0.7 on 2024-07-26 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_international_students_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=250, null=True)),
                ('send_on', models.DateTimeField(null=True)),
                ('h_student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.home_students')),
                ('i_student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.international_students')),
            ],
        ),
    ]
