# Generated by Django 5.0.7 on 2024-07-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='replay',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='message',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
