# Generated by Django 5.0.7 on 2024-07-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_messages_replay_alter_messages_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='replay',
            field=models.CharField(default='pending', max_length=500),
        ),
    ]
