# Generated by Django 5.0.7 on 2024-07-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_messages_replay'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='replay_on',
            field=models.DateTimeField(null=True),
        ),
    ]
