# Generated by Django 5.0.7 on 2024-07-27 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_messages_replay_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='replay',
            new_name='reply',
        ),
        migrations.RenameField(
            model_name='messages',
            old_name='replay_on',
            new_name='reply_on',
        ),
    ]
