# Generated by Django 5.0.7 on 2024-07-27 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_rename_replay_messages_reply_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_students',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
