# Generated by Django 5.0.7 on 2024-08-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_home_students_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='international_students',
            name='converted',
            field=models.BooleanField(default=False),
        ),
    ]
